### ISSUE TITLE
autocomplete-ansible unable to import ansible.

### ISSUE THREAD

**Issue by syodage** [h-hirokawa/atom-autocomplete-ansible#5]
When I install this package it shows me the following warning and it doesn't work either. I installed ansible using homebrew "brew install ansible". Mac OS X El Capitan.

autocomplete-ansible unable to import ansible.
Install ansible using pip.

**Comment by h-hirokawa** [comment]
Hi @shamrath,

When you install ansible with homebrew, the python packages are placed in a separated directory from global python `site-packages`.
So you must set `PYTHONPATH` environment variable to enable python to import ansible.

For example, when you want to use ansible 2.1.0.0 installed with brew, the procedure is as follows:

``` bash
$ export PYTHONPATH="/usr/local/Cellar/ansible/2.1.0.0/libexec/lib/python2.7/site-packages:/usr/local/Cellar/ansible/2.1.0.0/libexec/vendor/lib/python2.7/site-packages:$PYTHONPATH"
$ atom
```

You can see the actual `PYTHONPATH` in `/usr/local/bin/ansible`. This file is just a wrapper-script to execute ansible through brew.

FYI, I plan to add `PYTHONPATH` option to the settings in the next release.

Thanks.

**Comment by dakky** [comment]
Hello

I have a similar problem: I'm  switching my python environments via pyenv (https://github.com/yyuu/pyenv). 

As a result of this, my ansible setup ist located elsewhere:

```
which ansible python pip
/home/dakky/.pyenv/shims/ansible
/home/dakky/.pyenv/shims/python
/home/dakky/.pyenv/shims/pip
```

setting PYTHONPATH manually would work against pyload :S Is there any other "workaround"? Or maybe an option to skip such "pre checks" and hoping that the environment of the user is configured correctly? (I don't understand, how you are getting the information needed for autocompleting)

**Comment by aioue** [comment]
When running from a git checkout (rather than installing via pip etc), I have the same issue.

Would it be possible to specify ansible path in package settings?

_edit_: just seen you are intending to add the option in the next release. Any ETA?

**Comment by pruchai** [comment]
Same issue here. Please fix or give us a configuration option

**Comment by h-hirokawa** [comment]
@dakky @aioue @pruchai 
Now I added the `pythonPaths` option in v0.1.9.
Please try it.

**Comment by pruchai** [comment]
@h-hirokawa same issue. the the message only pops up when i open a new Atom window. Does not happen when the main one re-opens

`% head -1 /usr/local/bin/ansible`
`#!/usr/local/Cellar/ansible/2.2.0.0_1/libexec/bin/python2.7`

And the `pythonPaths` is set to `/usr/local/Cellar/ansible/2.2.0.0_1/libexec/bin/python2.7`

**Comment by h-hirokawa** [comment]
@pruchai 
`pythonPaths` option was not working properly when the atom project is not set.
I did fix for it, and additionally, now the plugin is activated only when a YAML file is opened.
So the issue should be fixed truly.

**Comment by pruchai** [comment]
Fix confirmed! Thank you for your help!

**Comment by ZeroDeth** [comment]
Fixed, Thanks.

`export PYTHONPATH="/usr/local/Cellar/ansible/2.2.1.0/libexec/lib/python2.7/site-packages:/usr/local/Cellar/ansible/2.2.1.0/libexec/vendor/lib/python2.7/site-packages:$PYTHONPATH"`

**Comment by noizo** [comment]
Still having this issue on macos sierra.
I have done:
`brew remove ansible`
`sudo pip uninstall ansible`
`sudo pip install ansible`

I have Atom 1.14.4

Anyway, autocomplete seems to work fine :)
